### ISSUE TITLE
buttons with no icons

### ISSUE THREAD

**Issue by MarcinPierzchalski** [SimpleTree/SimpleTreeRelease#1]
After restarting ubuntu 14.04 LTS (on virtualbox) and running program, I see buttons but with no icons. After cmake (without restarting) icons were present.
![screenshot from 2016-03-08 14 41 17](https://cloud.githubusercontent.com/assets/8359227/13603226/eda5eccc-e53b-11e5-956f-4313d29a131a.png)

**Comment by SimpleTree** [comment]
Thanks for the report. I was told private a similar occurence, also happening on virtualbox Ubuntu. As I develop on my Computree plugin of my method, I cannot follow up here anymore. If you are interested on Computree, which fully supports Windows, contact there please-
